# Dimensions
# orig - prev - 9, next - 23
# NUM_PREVIOUS_FRAME = 9
# NUM_NEXT_FRAME = 23
NUM_PREVIOUS_FRAME = 5
NUM_NEXT_FRAME = 11
NUM_FEATURES = 64
NUM_FRAMES = NUM_PREVIOUS_FRAME + NUM_NEXT_FRAME

# Audio
SAMPLE_RATE = 16000
TRUNCATE_SOUND_FIRST_SECONDS = 0.5

# Fliter Bank
USE_LOGSCALE = True
USE_DELTA = False
USE_SCALE = False
FILTER_BANK = NUM_FEATURES

# Mel
MEL_FEATURES = NUM_FEATURES

# IF
IF_FEATURES = NUM_FEATURES