# Dimensions
NUM_FEATURES = 128
NUM_FRAMES = 64

# Audio
SAMPLE_RATE = 48000
TRUNCATE_SOUND_FIRST_SECONDS = 0.5

# Fliter Bank
USE_LOGSCALE = True
USE_DELTA = False
USE_SCALE = False
FILTER_BANK = NUM_FEATURES

# Mel
MEL_FEATURES = NUM_FEATURES

# IF
IF_FEATURES = NUM_FEATURES